/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as DoctorIndexRouteImport } from './routes/doctor.index'
import { Route as PatientEducationRouteImport } from './routes/patient.education'
import { Route as PatientConsentRouteImport } from './routes/patient.consent'
import { Route as DoctorAuditRouteImport } from './routes/doctor.audit'
import { Route as DoctorPatientsIndexRouteImport } from './routes/doctor.patients.index'
import { Route as DoctorPatientsPatientIdRouteImport } from './routes/doctor.patients.$patientId'

const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/patient/',
  path: '/patient/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/doctor/',
  path: '/doctor/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientEducationRoute = PatientEducationRouteImport.update({
  id: '/patient/education',
  path: '/patient/education',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientConsentRoute = PatientConsentRouteImport.update({
  id: '/patient/consent',
  path: '/patient/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorAuditRoute = DoctorAuditRouteImport.update({
  id: '/doctor/audit',
  path: '/doctor/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorPatientsIndexRoute = DoctorPatientsIndexRouteImport.update({
  id: '/doctor/patients/',
  path: '/doctor/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorPatientsPatientIdRoute = DoctorPatientsPatientIdRouteImport.update({
  id: '/doctor/patients/$patientId',
  path: '/doctor/patients/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/doctor/audit': typeof DoctorAuditRoute
  '/patient/consent': typeof PatientConsentRoute
  '/patient/education': typeof PatientEducationRoute
  '/doctor/': typeof DoctorIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/doctor/patients/$patientId': typeof DoctorPatientsPatientIdRoute
  '/doctor/patients/': typeof DoctorPatientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/doctor/audit': typeof DoctorAuditRoute
  '/patient/consent': typeof PatientConsentRoute
  '/patient/education': typeof PatientEducationRoute
  '/doctor': typeof DoctorIndexRoute
  '/patient': typeof PatientIndexRoute
  '/doctor/patients/$patientId': typeof DoctorPatientsPatientIdRoute
  '/doctor/patients': typeof DoctorPatientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/doctor/audit': typeof DoctorAuditRoute
  '/patient/consent': typeof PatientConsentRoute
  '/patient/education': typeof PatientEducationRoute
  '/doctor/': typeof DoctorIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/doctor/patients/$patientId': typeof DoctorPatientsPatientIdRoute
  '/doctor/patients/': typeof DoctorPatientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/subscriptions'
    | '/doctor/audit'
    | '/patient/consent'
    | '/patient/education'
    | '/doctor/'
    | '/patient/'
    | '/doctor/patients/$patientId'
    | '/doctor/patients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/subscriptions'
    | '/doctor/audit'
    | '/patient/consent'
    | '/patient/education'
    | '/doctor'
    | '/patient'
    | '/doctor/patients/$patientId'
    | '/doctor/patients'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/subscriptions'
    | '/doctor/audit'
    | '/patient/consent'
    | '/patient/education'
    | '/doctor/'
    | '/patient/'
    | '/doctor/patients/$patientId'
    | '/doctor/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  DoctorAuditRoute: typeof DoctorAuditRoute
  PatientConsentRoute: typeof PatientConsentRoute
  PatientEducationRoute: typeof PatientEducationRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
  PatientIndexRoute: typeof PatientIndexRoute
  DoctorPatientsPatientIdRoute: typeof DoctorPatientsPatientIdRoute
  DoctorPatientsIndexRoute: typeof DoctorPatientsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/': {
      id: '/patient/'
      path: '/patient'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/doctor'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/education': {
      id: '/patient/education'
      path: '/patient/education'
      fullPath: '/patient/education'
      preLoaderRoute: typeof PatientEducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/consent': {
      id: '/patient/consent'
      path: '/patient/consent'
      fullPath: '/patient/consent'
      preLoaderRoute: typeof PatientConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/audit': {
      id: '/doctor/audit'
      path: '/doctor/audit'
      fullPath: '/doctor/audit'
      preLoaderRoute: typeof DoctorAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/patients/': {
      id: '/doctor/patients/'
      path: '/doctor/patients'
      fullPath: '/doctor/patients/'
      preLoaderRoute: typeof DoctorPatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/patients/$patientId': {
      id: '/doctor/patients/$patientId'
      path: '/doctor/patients/$patientId'
      fullPath: '/doctor/patients/$patientId'
      preLoaderRoute: typeof DoctorPatientsPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  DoctorAuditRoute: DoctorAuditRoute,
  PatientConsentRoute: PatientConsentRoute,
  PatientEducationRoute: PatientEducationRoute,
  DoctorIndexRoute: DoctorIndexRoute,
  PatientIndexRoute: PatientIndexRoute,
  DoctorPatientsPatientIdRoute: DoctorPatientsPatientIdRoute,
  DoctorPatientsIndexRoute: DoctorPatientsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
